CKEDITOR.replaceClass="wysiwyg";
CKEDITOR.basePath = '/pndrack/js/ckeditor/';
// CKEDITOR.config.baseHref = '/pndrack/';
CKEDITOR.config.resize_dir = 'both';
// CKEDITOR.config.width=400;
// CKEDITOR.config.height=400;
CKEDITOR.config.resize_enabled = true;
// CKEDITOR.config.resize_minWidth = 300;
// CKEDITOR.config.resize_maxWidth = 1024;