Select mn_id, mn_code, mn_parentid, mn_title, mn_status, mn_order, mn_group, mn_url, mn_webflag, mn_class, mn_classlist, mn_func, mn_funclist, mn_param, mn_pmscode from pflex.fcmenu
USE pflex;

insert into `fcmenu`(`mn_id`,`mn_code`,`mn_parentid`,`mn_title`,`mn_status`,`mn_order`,`mn_group`,`mn_url`,`mn_webflag`,`mn_class`,`mn_classlist`,`mn_func`,`mn_funclist`,`mn_param`,`mn_pmscode`) values (1,'HEADERMENU',0,'Top Menu','ACTIVE',0,null,'','Y',null,null,null,null,null,null);
insert into `fcmenu`(`mn_id`,`mn_code`,`mn_parentid`,`mn_title`,`mn_status`,`mn_order`,`mn_group`,`mn_url`,`mn_webflag`,`mn_class`,`mn_classlist`,`mn_func`,`mn_funclist`,`mn_param`,`mn_pmscode`) values (3,'DASHBOARD',1,'Dashboard','INACTIVE',1000,null,'','Y','Dashboard',null,'revenueyeartodate',null,null,null);
insert into `fcmenu`(`mn_id`,`mn_code`,`mn_parentid`,`mn_title`,`mn_status`,`mn_order`,`mn_group`,`mn_url`,`mn_webflag`,`mn_class`,`mn_classlist`,`mn_func`,`mn_funclist`,`mn_param`,`mn_pmscode`) values (4,'SHELF',1,'Shelf','INACTIVE',2000,null,'','Y','Shelf',null,'Home',null,null,null);
insert into `fcmenu`(`mn_id`,`mn_code`,`mn_parentid`,`mn_title`,`mn_status`,`mn_order`,`mn_group`,`mn_url`,`mn_webflag`,`mn_class`,`mn_classlist`,`mn_func`,`mn_funclist`,`mn_param`,`mn_pmscode`) values (5,'REPORT',1,'Report','ACTIVE',3000,null,'','Y','Report',null,'rptrevdaily',null,null,null);
insert into `fcmenu`(`mn_id`,`mn_code`,`mn_parentid`,`mn_title`,`mn_status`,`mn_order`,`mn_group`,`mn_url`,`mn_webflag`,`mn_class`,`mn_classlist`,`mn_func`,`mn_funclist`,`mn_param`,`mn_pmscode`) values (6,'SETTING',1,'Setting','ACTIVE',4000,'VW_SETTING, VW_CLISETTING, VW_ADMSETTING',null,'Y','Setting',null,'gensetting',null,null,'VW_SETTING, VW_CLISETTING, VW_ADMSETTING');
insert into `fcmenu`(`mn_id`,`mn_code`,`mn_parentid`,`mn_title`,`mn_status`,`mn_order`,`mn_group`,`mn_url`,`mn_webflag`,`mn_class`,`mn_classlist`,`mn_func`,`mn_funclist`,`mn_param`,`mn_pmscode`) values (12,'RPTAGING',5,'Aging Report','ACTIVE',3100,null,'','Y','Report',null,'rptaging',null,null,null);
insert into `fcmenu`(`mn_id`,`mn_code`,`mn_parentid`,`mn_title`,`mn_status`,`mn_order`,`mn_group`,`mn_url`,`mn_webflag`,`mn_class`,`mn_classlist`,`mn_func`,`mn_funclist`,`mn_param`,`mn_pmscode`) values (21,'GENSETTING',6,'General Setting','ACTIVE',4100,null,null,'Y','Setting',null,'gensetting',null,null,'VW_SETTING');
insert into `fcmenu`(`mn_id`,`mn_code`,`mn_parentid`,`mn_title`,`mn_status`,`mn_order`,`mn_group`,`mn_url`,`mn_webflag`,`mn_class`,`mn_classlist`,`mn_func`,`mn_funclist`,`mn_param`,`mn_pmscode`) values (40,'SHELFSETTING',6,'Shelf Setting','ACTIVE',4200,'VW_CLISETTING',null,'Y','Setting','','shelfSetting','','','VW_CLISETTING');
insert into `fcmenu`(`mn_id`,`mn_code`,`mn_parentid`,`mn_title`,`mn_status`,`mn_order`,`mn_group`,`mn_url`,`mn_webflag`,`mn_class`,`mn_classlist`,`mn_func`,`mn_funclist`,`mn_param`,`mn_pmscode`) values (41,'DSHELFSETTING',40,'Shelf Setting','ACTIVE',4210,'VW_CLISETTING',null,'Y','Setting','','shelfSetting','','','VW_CLISETTING');
insert into `fcmenu`(`mn_id`,`mn_code`,`mn_parentid`,`mn_title`,`mn_status`,`mn_order`,`mn_group`,`mn_url`,`mn_webflag`,`mn_class`,`mn_classlist`,`mn_func`,`mn_funclist`,`mn_param`,`mn_pmscode`) values (42,'SHELFGSETTING',40,'Shelf Group Setting','ACTIVE',4220,'VW_CLISETTING',null,'Y','Setting','','shelfGroupSetting','','','VW_CLISETTING');
insert into `fcmenu`(`mn_id`,`mn_code`,`mn_parentid`,`mn_title`,`mn_status`,`mn_order`,`mn_group`,`mn_url`,`mn_webflag`,`mn_class`,`mn_classlist`,`mn_func`,`mn_funclist`,`mn_param`,`mn_pmscode`) values (43,'MAIN',1,'Main','ACTIVE',1000,'VW_MAIN',null,'Y','Main','','board','','','VW_MAIN');
insert into `fcmenu`(`mn_id`,`mn_code`,`mn_parentid`,`mn_title`,`mn_status`,`mn_order`,`mn_group`,`mn_url`,`mn_webflag`,`mn_class`,`mn_classlist`,`mn_func`,`mn_funclist`,`mn_param`,`mn_pmscode`) values (44,'CUSTOMER',43,'Customer List','ACTIVE',1200,'VW_MAIN',null,'Y','Main','','customer','','','VW_MAIN');
insert into `fcmenu`(`mn_id`,`mn_code`,`mn_parentid`,`mn_title`,`mn_status`,`mn_order`,`mn_group`,`mn_url`,`mn_webflag`,`mn_class`,`mn_classlist`,`mn_func`,`mn_funclist`,`mn_param`,`mn_pmscode`) values (45,'SEARCHPLATE',43,'Search Plate','ACTIVE',1100,'VW_MAIN',null,'Y','Main','','searchplate','','','VW_MAIN');
insert into `fcmenu`(`mn_id`,`mn_code`,`mn_parentid`,`mn_title`,`mn_status`,`mn_order`,`mn_group`,`mn_url`,`mn_webflag`,`mn_class`,`mn_classlist`,`mn_func`,`mn_funclist`,`mn_param`,`mn_pmscode`) values (46,'OPERATION',1,'Operation','ACTIVE',2000,'VW_OPERATION',null,'Y','rackOperation','checkinout',null,'','','VW_OPERATION');
insert into `fcmenu`(`mn_id`,`mn_code`,`mn_parentid`,`mn_title`,`mn_status`,`mn_order`,`mn_group`,`mn_url`,`mn_webflag`,`mn_class`,`mn_classlist`,`mn_func`,`mn_funclist`,`mn_param`,`mn_pmscode`) values (47,'CHECKINOUT',46,'Check In/Out','ACTIVE',2100,'VW_OPERATION',null,'Y','rackOperation','checkinout','checkinout','','','VW_OPERATION');
insert into `fcmenu`(`mn_id`,`mn_code`,`mn_parentid`,`mn_title`,`mn_status`,`mn_order`,`mn_group`,`mn_url`,`mn_webflag`,`mn_class`,`mn_classlist`,`mn_func`,`mn_funclist`,`mn_param`,`mn_pmscode`) values (48,'STOCKCNT',46,'Stock Count','ACTIVE',2200,'VW_OPERATION',null,'Y','rackOperation','stockcount','stockcount','','','VW_OPERATION');
insert into `fcmenu`(`mn_id`,`mn_code`,`mn_parentid`,`mn_title`,`mn_status`,`mn_order`,`mn_group`,`mn_url`,`mn_webflag`,`mn_class`,`mn_classlist`,`mn_func`,`mn_funclist`,`mn_param`,`mn_pmscode`) values (49,'CREATEPLATE',43,'Create Plate','ACTIVE',1050,'VW_MAIN',null,'Y','Main',null,'createplate',null,null,'VW_MAIN');
insert into `fcmenu`(`mn_id`,`mn_code`,`mn_parentid`,`mn_title`,`mn_status`,`mn_order`,`mn_group`,`mn_url`,`mn_webflag`,`mn_class`,`mn_classlist`,`mn_func`,`mn_funclist`,`mn_param`,`mn_pmscode`) values (50,'USERSETT',6,'Primary User Setting','ACTIVE',4300,'VW_SETTING',null,'Y','Setting','','usersetup','','','VW_ADMSETTING, VW_SETTING');
insert into `fcmenu`(`mn_id`,`mn_code`,`mn_parentid`,`mn_title`,`mn_status`,`mn_order`,`mn_group`,`mn_url`,`mn_webflag`,`mn_class`,`mn_classlist`,`mn_func`,`mn_funclist`,`mn_param`,`mn_pmscode`) values (52,'USERSETUP',50,'User Setup','ACTIVE',4310,'VW_SETTING',null,'Y','Setting','','usersetup','','','VW_SETTING');
insert into `fcmenu`(`mn_id`,`mn_code`,`mn_parentid`,`mn_title`,`mn_status`,`mn_order`,`mn_group`,`mn_url`,`mn_webflag`,`mn_class`,`mn_classlist`,`mn_func`,`mn_funclist`,`mn_param`,`mn_pmscode`) values (53,'ROLESETUP',50,'Role Setup','ACTIVE',4320,'VW_SETTING',null,'Y','Setting','','rolesetup','','','VW_SETTING');
insert into `fcmenu`(`mn_id`,`mn_code`,`mn_parentid`,`mn_title`,`mn_status`,`mn_order`,`mn_group`,`mn_url`,`mn_webflag`,`mn_class`,`mn_classlist`,`mn_func`,`mn_funclist`,`mn_param`,`mn_pmscode`) values (54,'PERMSETUP',50,'Permission Setup','ACTIVE',4330,'VW_SETTING',null,'Y','Setting','','permissionsetup','','','VW_SETTING');
insert into `fcmenu`(`mn_id`,`mn_code`,`mn_parentid`,`mn_title`,`mn_status`,`mn_order`,`mn_group`,`mn_url`,`mn_webflag`,`mn_class`,`mn_classlist`,`mn_func`,`mn_funclist`,`mn_param`,`mn_pmscode`) values (55,'ORGSETUP',6,'Org Setting','ACTIVE',4300,'VW_SETTING, VW_ADMSETTING',null,'Y','Setting',null,'org',null,null,'VW_SETTING, VW_ADMSETTING');
insert into `fcmenu`(`mn_id`,`mn_code`,`mn_parentid`,`mn_title`,`mn_status`,`mn_order`,`mn_group`,`mn_url`,`mn_webflag`,`mn_class`,`mn_classlist`,`mn_func`,`mn_funclist`,`mn_param`,`mn_pmscode`) values (57,'PCKGSETUP',6,'Package Setup','ACTIVE',4300,'VW_SETTING',null,'Y','Setting',null,'packagesetup',null,null,'VW_SETTING');
insert into `fcmenu`(`mn_id`,`mn_code`,`mn_parentid`,`mn_title`,`mn_status`,`mn_order`,`mn_group`,`mn_url`,`mn_webflag`,`mn_class`,`mn_classlist`,`mn_func`,`mn_funclist`,`mn_param`,`mn_pmscode`) values (70,'MENUSETTING',6,'Menu Setup','ACTIVE',4400,'VW_SETTING',null,'Y','Setting','','menusetup','','','VW_SETTING');
insert into `fcmenu`(`mn_id`,`mn_code`,`mn_parentid`,`mn_title`,`mn_status`,`mn_order`,`mn_group`,`mn_url`,`mn_webflag`,`mn_class`,`mn_classlist`,`mn_func`,`mn_funclist`,`mn_param`,`mn_pmscode`) values (71,'CLIUSERSETT',6,'User Setup','ACTIVE',null,'VW_SETTING, VW_CLISETTING',null,'Y','Setting',null,'cusersetup',null,null,'VW_SETTING, VW_CLISETTING');
